CREATE DATABASE IF NOT EXISTS QUEUE;
USE QUEUE;

CREATE TABLE PROCESSING_QUEUE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IMAGE_ID INT NOT NULL,
    MODEL_ID INT NOT NULL,
    CLASSIFICATION_REPORT_ID INT,
    SEGMENTATION_REPORT_ID INT,
    IMAGE MEDIUMBLOB NOT NULL,
    GENERATE_MASK BOOLEAN,
    UNIQUE (IMAGE_ID, MODEL_ID)
);

CREATE TABLE VALIDATION_QUEUE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IMAGE_ID INT NOT NULL,
    VALIDATION_MODEL_ID INT NOT NULL,
    MODEL_ID INT NOT NULL,
    CLASSIFICATION_REPORT_ID INT,
    SEGMENTATION_REPORT_ID INT,
    IMAGE MEDIUMBLOB NOT NULL,
    GENERATE_MASK BOOLEAN,
    UNIQUE (IMAGE_ID, MODEL_ID)
);

CREATE TABLE BUFFER (
    ID INT PRIMARY KEY,
    IMAGE_ID INT NOT NULL,
    MODEL_ID INT NOT NULL,
    CLASSIFICATION_REPORT_ID INT,
    SEGMENTATION_REPORT_ID INT,
    IMAGE MEDIUMBLOB NOT NULL,
    GENERATE_MASK BOOLEAN,
    UNIQUE (IMAGE_ID, MODEL_ID)
);