CREATE DATABASE IF NOT EXISTS STORAGE;
USE STORAGE;

CREATE TABLE IMAGE(
    ID INT PRIMARY KEY, -- SAME AS DB.IMAGE.ID
    DATA MEDIUMBLOB NOT NULL
);

CREATE TABLE MASK(
    ID INT PRIMARY KEY, -- SAME AS DB.SEGMENTATION_REPORT.ID
    DATA MEDIUMBLOB NOT NULL
);

CREATE TABLE WEIGHTS(
    ID INT PRIMARY KEY, -- SAME AS DB.MODEL.ID
    DATA LONGBLOB NOT NULL
);
