CREATE USER 'CONSUMER_DB'@'%' IDENTIFIED BY 'CONSUMER_DB_PASSWORD';
CREATE USER 'CONSUMER_QUEUE'@'%' IDENTIFIED BY 'CONSUMER_QUEUE_PASSWORD';
CREATE USER 'CONSUMER_STORAGE'@'%' IDENTIFIED BY 'CONSUMER_STORAGE_PASSWORD';
CREATE USER 'INSERT_MODEL_DB'@'%' IDENTIFIED BY 'INSERT_MODEL_DB_PASSWORD';
CREATE USER 'INSERT_MODEL_STORAGE'@'%' IDENTIFIED BY 'INSERT_MODEL_STORAGE_PASSWORD';
CREATE USER 'ENQUEUE_REPORT_DB'@'%' IDENTIFIED BY 'ENQUEUE_REPORT_DB_PASSWORD';
CREATE USER 'ENQUEUE_REPORT_QUEUE'@'%' IDENTIFIED BY 'ENQUEUE_REPORT_QUEUE_PASSWORD';
CREATE USER 'ENQUEUE_REPORT_STORAGE'@'%' IDENTIFIED BY 'ENQUEUE_REPORT_STORAGE_PASSWORD';
CREATE USER 'API_DB'@'%' IDENTIFIED BY 'API_DB_PASSWORD';
CREATE USER 'API_QUEUE'@'%' IDENTIFIED BY 'API_QUEUE_PASSWORD';
CREATE USER 'API_STORAGE'@'%' IDENTIFIED BY 'API_STORAGE_PASSWORD';

GRANT SELECT ON DB.MODEL_CATEGORY TO 'CONSUMER_DB'@'%';
GRANT SELECT ON DB.MODEL_TYPE TO 'CONSUMER_DB'@'%';
GRANT SELECT ON DB.MODEL TO 'CONSUMER_DB'@'%';
GRANT SELECT ON DB.DISEASE TO 'CONSUMER_DB'@'%';
GRANT SELECT ON DB.SEVERITY TO 'CONSUMER_DB'@'%';
GRANT SELECT, UPDATE ON DB.CLASSIFICATION_REPORT TO 'CONSUMER_DB'@'%';
GRANT SELECT, UPDATE ON DB.SEGMENTATION_REPORT TO 'CONSUMER_DB'@'%';

GRANT LOCK TABLES ON QUEUE.* TO 'CONSUMER_QUEUE'@'%';
GRANT SELECT, INSERT, DELETE ON QUEUE.PROCESSING_QUEUE TO 'CONSUMER_QUEUE'@'%';
GRANT SELECT, DELETE ON QUEUE.VALIDATION_QUEUE TO 'CONSUMER_QUEUE'@'%';
GRANT SELECT, INSERT, DELETE ON QUEUE.BUFFER TO 'CONSUMER_QUEUE'@'%';

GRANT INSERT ON STORAGE.MASK TO 'CONSUMER_STORAGE'@'%';
GRANT SELECT ON STORAGE.WEIGHTS TO 'CONSUMER_STORAGE'@'%';

GRANT SELECT, INSERT ON DB.MODEL TO 'INSERT_MODEL_DB'@'%';
GRANT SELECT ON DB.MODEL_CATEGORY TO 'INSERT_MODEL_DB'@'%';
GRANT SELECT ON DB.MODEL_TYPE TO 'INSERT_MODEL_DB'@'%';

GRANT INSERT ON STORAGE.WEIGHTS TO 'INSERT_MODEL_STORAGE'@'%';

GRANT SELECT ON DB.MODEL TO 'ENQUEUE_REPORT_DB'@'%';
GRANT SELECT ON DB.MODEL_CATEGORY TO 'ENQUEUE_REPORT_DB'@'%';
GRANT SELECT ON DB.MODEL_TYPE TO 'ENQUEUE_REPORT_DB'@'%';
GRANT INSERT ON DB.IMAGE TO 'ENQUEUE_REPORT_DB'@'%';
GRANT INSERT ON DB.CLASSIFICATION_REPORT TO 'ENQUEUE_REPORT_DB'@'%';
GRANT INSERT ON DB.SEGMENTATION_REPORT TO 'ENQUEUE_REPORT_DB'@'%';

GRANT INSERT ON QUEUE.PROCESSING_QUEUE TO 'ENQUEUE_REPORT_QUEUE'@'%';
GRANT INSERT ON QUEUE.VALIDATION_QUEUE TO 'ENQUEUE_REPORT_QUEUE'@'%';

GRANT INSERT ON STORAGE.IMAGE TO 'ENQUEUE_REPORT_STORAGE'@'%';

GRANT SELECT ON DB.ACCOUNT_TYPE TO 'API_DB'@'%';
GRANT SELECT ON DB.REGISTER_TYPE TO 'API_DB'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON DB.USER TO 'API_DB'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON DB.TECHNICIAN TO 'API_DB'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON DB.PRODUCER TO 'API_DB'@'%';
GRANT SELECT ON DB.MODEL_CATEGORY TO 'API_DB'@'%';
GRANT SELECT ON DB.MODEL_TYPE TO 'API_DB'@'%';
GRANT SELECT ON DB.MODEL TO 'API_DB'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON DB.IMAGE TO 'API_DB'@'%';
GRANT SELECT ON DB.DISEASE TO 'API_DB'@'%';
GRANT SELECT ON DB.SEVERITY TO 'API_DB'@'%';
GRANT SELECT, INSERT ON DB.CLASSIFICATION_REPORT TO 'API_DB'@'%';
GRANT SELECT, INSERT ON DB.SEGMENTATION_REPORT TO 'API_DB'@'%';

GRANT SELECT, INSERT ON QUEUE.PROCESSING_QUEUE TO 'API_QUEUE'@'%';
GRANT SELECT, INSERT ON QUEUE.VALIDATION_QUEUE TO 'API_QUEUE'@'%';

GRANT SELECT, INSERT, DELETE ON STORAGE.IMAGE TO 'API_STORAGE'@'%';
GRANT SELECT, DELETE ON STORAGE.MASK TO 'API_STORAGE'@'%';

FLUSH PRIVILEGES;