[interfaces]

[interfaces.database]
module = "mysql"

[interfaces.database.mysql]
class = "MySQLDatabase"
host = "mysql"
port = 3306
user = "INSERT_MODEL_DB"
password = "INSERT_MODEL_DB_PASSWORD"
database = "DB"

[interfaces.storage]
module = "mysql"

[interfaces.storage.mysql]
class = "MySQLStorage"
host = "mysql"
port = 3306
user = "INSERT_MODEL_STORAGE"
password = "INSERT_MODEL_STORAGE_PASSWORD"
database = "STORAGE"
