CREATE DATABASE IF NOT EXISTS DB;
USE DB;

CREATE TABLE ACCOUNT_TYPE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    UNIQUE (NAME)
);

CREATE TABLE REGISTER_TYPE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    UNIQUE (NAME)
);

CREATE TABLE USER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    REGISTER_TYPE_ID INT NOT NULL,
    ACCOUNT_TYPE_ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    TELEPHONE VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    TOKEN_UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    TOKEN_LOGIN VARCHAR(255),
    TOKEN_ATTEMPTS INT DEFAULT 0,
    FOREIGN KEY (REGISTER_TYPE_ID) REFERENCES REGISTER_TYPE(ID),
    FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES ACCOUNT_TYPE(ID)
);

CREATE TABLE TECHNICIAN (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    PROFESSIONAL_QUALIFICATION VARCHAR(255) NOT NULL,
    OCCUPATION_AREA VARCHAR(255) NOT NULL,
    COUNCIL_REGISTRATION VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    EVALUATION TEXT,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE PRODUCER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    COFFEE_TYPE VARCHAR(255) NOT NULL,
    PROPERTY_SIZE VARCHAR(255),
    PRODUCTION INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE MODEL_CATEGORY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    UNIQUE (NAME)
);

CREATE TABLE MODEL_TYPE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    UNIQUE (NAME)
);

CREATE TABLE MODEL (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MODEL_CATEGORY_ID INT NOT NULL,
    MODEL_TYPE_ID INT NOT NULL,
    SUBTYPE VARCHAR(100) NOT NULL,
    MODULE VARCHAR(100) NOT NULL,
    CLASS VARCHAR(100) NOT NULL,
    VERSION VARCHAR(100) NOT NULL,
    REGISTERED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    ENABLED BOOLEAN NOT NULL,
    UNIQUE (MODEL_CATEGORY_ID, MODEL_TYPE_ID, SUBTYPE, MODULE, CLASS, VERSION),
    FOREIGN KEY (MODEL_CATEGORY_ID) REFERENCES MODEL_CATEGORY(ID),
    FOREIGN KEY (MODEL_TYPE_ID) REFERENCES MODEL_TYPE(ID)
);

CREATE TABLE IMAGE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    FILENAME VARCHAR(255) NOT NULL,
    UPLOADED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE DISEASE (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    TREATMENT VARCHAR(255),
    PREVENTION VARCHAR(255),
    UNIQUE (NAME)
);

CREATE TABLE SEVERITY (
    ID INT PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL,
    UNIQUE (DESCRIPTION)
);

CREATE TABLE CLASSIFICATION_REPORT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    IMAGE_ID INT NOT NULL,
    MODEL_ID INT NOT NULL,
    DISEASE_ID INT,
    SEVERITY_ID INT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PROCESSED_AT DATETIME,
    VALID BOOLEAN,
    UNIQUE (IMAGE_ID, MODEL_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (IMAGE_ID) REFERENCES IMAGE(ID),
    FOREIGN KEY (MODEL_ID) REFERENCES MODEL(ID),
    FOREIGN KEY (DISEASE_ID) REFERENCES DISEASE(ID),
    FOREIGN KEY (SEVERITY_ID) REFERENCES SEVERITY(ID)
);

CREATE TABLE SEGMENTATION_REPORT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    IMAGE_ID INT NOT NULL,
    MODEL_ID INT NOT NULL,
    STRESS_RATIO FLOAT,
    SEVERITY_ID INT,
    HAS_MASK BOOLEAN NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PROCESSED_AT DATETIME,
    VALID BOOLEAN,
    UNIQUE (IMAGE_ID, MODEL_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (IMAGE_ID) REFERENCES IMAGE(ID),
    FOREIGN KEY (MODEL_ID) REFERENCES MODEL(ID),
    FOREIGN KEY (SEVERITY_ID) REFERENCES SEVERITY(ID)
);

INSERT INTO MODEL_CATEGORY (NAME) VALUES ('VALIDATION');
INSERT INTO MODEL_CATEGORY (NAME) VALUES ('PROCESSING');

INSERT INTO MODEL_TYPE (NAME) VALUES ('CLASSIFICATION');
INSERT INTO MODEL_TYPE (NAME) VALUES ('SEGMENTATION');
INSERT INTO MODEL_TYPE (NAME) VALUES ('COFFEE_LEAF_OCC');

INSERT INTO DISEASE (ID, NAME, DESCRIPTION, TREATMENT, PREVENTION) VALUES (0, 'healthy', 'Saudável, sem sintomas.', 'Não aplicável.', 'Manter boas práticas agrícolas.');
INSERT INTO DISEASE (ID, NAME, DESCRIPTION, TREATMENT, PREVENTION) VALUES (1, 'leaf miner', 'Minador de folhas causa danos diretos à fotossíntese.', 'Uso de inseticidas específicos e controle biológico.', 'Monitoramento regular e eliminação de plantas infectadas.');
INSERT INTO DISEASE (ID, NAME, DESCRIPTION, TREATMENT, PREVENTION) VALUES (2, 'rust', 'Ferrugem do café é uma doença que afeta as folhas, reduzindo a capacidade de fotossíntese.', 'Aplicação de fungicidas e manejo integrado de doenças.', 'Uso de variedades resistentes e eliminação de folhas infectadas.');
INSERT INTO DISEASE (ID, NAME, DESCRIPTION, TREATMENT, PREVENTION) VALUES (3, 'phoma', 'Phoma é uma doença fúngica que afeta as folhas e ramos.', 'Podas sanitárias e aplicação de fungicidas.', 'Evitar ferimentos nas plantas e realizar rotação de culturas.');
INSERT INTO DISEASE (ID, NAME, DESCRIPTION, TREATMENT, PREVENTION) VALUES (4, 'cercospora', 'Cercospora causa manchas nas folhas, afetando a fotossíntese.', 'Uso de fungicidas e manejo da nutrição da planta.', 'Manter distância adequada entre as plantas e evitar excesso de umidade.');

INSERT INTO SEVERITY (ID, DESCRIPTION) VALUES (0, 'Menor que 0,1%');
INSERT INTO SEVERITY (ID, DESCRIPTION) VALUES (1, 'Entre 0,1% e 5%');
INSERT INTO SEVERITY (ID, DESCRIPTION) VALUES (2, 'Entre 5% e 10%');
INSERT INTO SEVERITY (ID, DESCRIPTION) VALUES (3, 'Entre 10% e 15%');
INSERT INTO SEVERITY (ID, DESCRIPTION) VALUES (4, 'Maior que 15%');